package nimittachoodamanicore

func getAnswer(dice string) string {
	return answerMap[dice]
}

var answerMap = map[string]string{
	"111":       "This is a Bad Sakuna. Don't make friendship. Don't do that work. If you do it you will lose your name and fame. May not be fulfilled.",
	"112":       "This is a Good Sakuna/Omen. The outcome will be fruitful with the grace of (Thiru Venkatadri) Lord of Seven Hills. You may have a doubt in it. It will take a good shape. Don't worry.",
	"1110":      "This is a Bad Sakuna/Omen. Whatever you propose thinking that it can be done will not be fulfilled. Leave it.",
	"11100":     "This is a good Sakuna. With the grace of Lord Siva you will be completing the work. You can expect reunion of those who have left long back. Will lead a peaceful life with comforts.",
	"121":       "This is a Good Sakuna. With the grace of Goddess Veera Lakshmi the proposed work will be fruitful even though it seems very difficult. Don't worry.",
	"122":       "This Sakuna/Omen is Good. The proposal will be fruitful with the grace of Goddess Parvathi Matha. You may have a good relationship with that person don't spoil it.",
	"1210":      "This is a Bad Sakuna. The proposed work may not be fruitful. You may feel bad and sad.",
	"12100":     "This is a bad Omen/Sakuna. The question you have asked is a confidential one. No God's grace. Don't believe that person. If you believe in him there may be a threat to your life no doubt.",
	"1101":      "This is a bad Sakuna. The outcome of the question you have asked will not be fruitful. You may lose it. You may lose your job also. Crop also will not yield.",
	"1102":      "This is a Good Sakuna. With the grace of Lord Mallikarjuna the proposal will be fruitful. You will be appreciated by all well being can be expected.",
	"11010":     "This is a Good Sakuna/Omen the work for which you have asked will be done like reopening of a closed house you may undertake a Sea travel with the grace of Dharmaraja.",
	"110100":    "This is a Good Sakuna with the grace of Lord Parameswara will lead peaceful life proposal will be fruitful no doubt.",
	"11001":     "This is a Good Sakunawith the grace of Lord Dharmaraja you will win over your enemy. On keen observation it will be fruitful. You can expect good result. Don't worry.",
	"11002":     "This is a Good Sakuna/Omen. With the grace of Lord Siva you will win over your good old enemies there is no doubt. Things will settle down.",
	"110010":    "This is a Bad Sakuna/Omen. You may initiate the work. It will not be fruitful. So leave it else it may lead to extremes and danger to life.",
	"1100100":   "This is a Good Sakuna; the proposed work will be completed with the grace of Dharmaraja without any quarrels. You can expect good result. Don't worry.",
	"211":       "This is a Good Sakuna/Omen. The question you have put before will be fruitful with the grace of Lord Sadasiva. The travel proposed will also be fruitful.",
	"212":       "This is a Good Sakuna. With the grace of Lord Parameswara whatever you propose will be successful that too as quick as possible.",
	"2110":      "This is a good Sakuna/Omen. With the grace of Lord Dharmaraja it will be fruitful. you have to wait for 20 days. Don't worry.",
	"21100":     "This is a Good Sakuna/Omen. The Proposal will be fruitful with the blessing of Lord Narasimhadisease will be cured. The money will reach in time will be free from hurdles.",
	"221":       "This is a bad Sakuna/Omen. Don't undertake this proposal. If you undertake It will not be fruitful. Enemies are furious on you. You may hear a bad news.",
	"222":       "This is a Good Sakuna. With the grace of Lord Sadasiva you will be free from planetary ill effects. You may have an enemy. Ignore him. The proposal will be fruitful.",
	"2210":      "This is a Good Sakuna/Omen. The proposed task will be fruitful with the god's grace. Don't worry disease will be cured. Good result can be expected shortly.",
	"22100":     "This is a Good Sakuna/Omen. The work you have proposed will be fruitful with the grace of Lord Sri Krishna. Disease will be cured; can expect the money in time. You will be free from hurdles.",
	"2101":      "This is a Bad Sakuna. Don't tell it to anybody don't believe that he is your relative, if you believe in him,danger is indicated. Be careful.",
	"2102":      "This is a Good Sakuna/Omen. With the grace of Lord Gangadhar you will recover the bad debts. Planetary ill effects will be ruled out. Don't worry.",
	"21010":     "This is a Bad Omen/Sakuna. No use. If you take help of a person even then no use. Don't do it leave it.",
	"210100":    "This is a Good Sakuna/Omen. With the grace of Lord Narayana the work will be completed in time, no doubt about it.",
	"21001":     "This is a Good Sakuna/Omen. The task undertaken will be fruitful with the grace of Lord Narasimha. In the first instance you may lose. At a later stage you may gain what you have lost as was experienced by Dharmaraja by losing everything on betting and later gained with the blessings of Lord Krishna.",
	"21002":     "This is a Good Sakuna/Omen. The proposed work will be fruitful with the grace of Lord Janardhana. You will get that Job/Business. But will take time, the person(s) who have left you will re-unite. Don't worry",
	"210010":    "This is a Good Sakuna/Omen. With the grace of Lord Siva. The proposal will be fruitful.",
	"2100100":   "This is a Good Sakuna/Omen. With the grace of Lord Mallikarjuna. The question you are asking will be fruitful. Your relatives who are living in foreign lands may visit.",
	"1011":      "This is a bad Sakuna/Omen. The work proposed will not be fruitful. The plans proposed this day will also be not fruitful. ",
	"1012":      "This is a Good Sakuna/Omen. With the grace of Lord Indivaraksha your proposal will be fruitful. You may lead a better life. Good news can be expected. ",
	"10110":     "This is a Good Sakuna. With the grace of Goddess Kamakshi the works proposed will be fruitful. Can expect well being with comforts.",
	"101100":    "This is a Good Sakuna/Omen. With the grace of Bharata it will be fruitful. You will be succeed in this issue. No cunning plans. Don't worry. ",
	"1021":      "This is a Good Sakuna. With the blessing of Goddess Lakshmi the question you have asked will be fruitful. Your ambitions will be fulfilled. ",
	"1022":      "This is a Good Sakuna. With the grace of Lord Ganesh. Though it is difficult task you can reach your goal. The proposed work will be fruitful. No confusion just go ahead.",
	"10210":     "This is a good Sakuna/Omen. With the grace of Lord Kshetrapala . The previous ill effects will be ruled out. No doubt in it. Don't worry. You can expect a good result.",
	"102100":    "This is a Good Sakuna. The proposal will be fruitful with the grace of Goddess Bhoodevi. No difficulties at all. Bright future can be expected.",
	"10101":     "This is a good Sakuna/Omen. With the grace of Lord Rama you may Travel towards western side. The work you have started will be fruitful. Stop secret dealings with that person.",
	"10102":     "This is a Good Sakuna/Omen. With the grace of Lord Indra's son you may undertake a travel. The task proposed will be fruitful. Good.",
	"101010":    "This is a Good Sakuna. With the grace of Varunadeva difficulties in the proposed task will be solved. You will receive money. You will be free from hurdles. Things will settle. Don't worry.",
	"1010100":   "This is a Good Sakuna/Omen. With the grace of Lord Trayabikathere are no ill effects in the proposed task. Don't worry.",
	"101001":    "This is a bad Sakuna. No Gods grace, even though you work hard it will not be fruitful. So leave it",
	"101002":    "This is a Good Sakuna/Omen. As Arjuna has gained pasupatastra as boon from Lord Siva your will and wish will be fruitful and completed. Work hard. Don't leave it.",
	"1010010":   "This is a Bad Sakuna. No God's grace. Don't do evil deeds. Leave the task.",
	"10100100":  "This is a Good Sakuna, with the grace of Lord Viswanatha all the ill effects will be ruled out the work proposed will be fruitful go ahead.",
	"10011":     "This is a Good Sakuna with the grace of Lord Tripurantaka you may buy new clothscan expect good result don't worry.",
	"10012":     "This is a Bad Sakuna. Think twice before you act. Don't believe that person the proposed work may not be fruitful.",
	"100110":    "This is a good Sakuna/Omen. Your proposal will be fruitful with the blessings of Lord Lakshmi Narayana. You may undertake a sea journey. Good.",
	"1001100":   "This is a Bad Sakuna. No God's grace, you cannot undertake it, if at all undertaken you may come out with a great struggle with a moderate result. It is not worthy task leave it.",
	"10021":     "This is a Good Sakuna. With the grace of Lord Vishnuthe proposal will be fruitfulplanetary ill effects will be cleared. No feargo ahead.",
	"10022":     "This is a Bad Sakuna. The proposal will be spoiled by a person, don't do it, leave it.",
	"100210":    "This is a Good Sakuna. With the grace of Lord Parameswara whatever work you propose will be fruitful that too as quick as possible. Good life expected.",
	"1002100":   "This is a Good Sakuna. With the grace of Lord Eswara the proposal will be fruitful don't worry.",
	"100101":    "This is a Good Sakuna with the grace of Lord Jagannadha well being can be expected. There may be a quarrel but it will settle down. Good results can be expected.",
	"100102":    "This is a good Sakuna/Omen. The question you have asked will be fruitful without any problems with the grace of Lord Viswanatha. Well being with comforts can be expected. ",
	"1001010":   "This is a Good Sakuna. The task you have undertaken will be successful with the grace of Goddess Durga and Lord Parameswar.",
	"10010100":  "This is a Bad Omen/Sakuna. The Proposed task will not be fruitful. The other works already undertaken will not be completed. Don't feel much. Stop feeling.",
	"1001001":   "This is a Good Sakuna. With the grace of Lord Koormanatha No ill effects. Don't worry well being can be expected.",
	"1001002":   "This is a Good Sakuna. With the grace of Lord Kanchi Varadaraja Swamy you will get relief from planetary ill effects. Well being can be expected with the grace of Lord Sarveswara.",
	"10010010":  "This is a Good Sakuna/Omen. The work you have asked will be fruitful with the blessing of Goddess Durga. You will win. You will be gained. Don't worry.",
	"100100100": "This is a Good Sakuna/Omen. The question you have asked will be completed with the grace of Lord Kasi Viswanatha. Bad debts will be recovered. Can expect Good news. Don't worry.",
}
